Da bi mogli raditi sa modulom numpy moramo ga 
prvo importovati, to ćemo učiniti u ćeliji ispod

In [1]:
import numpy as np

import - je ključna riječ pomoću koje uvodimo modul u svesku,
numpy - je naziv modula

as - ključna riječ je kada želimo dati skraćenicu nekom objektu, u našem slučaju je to modul numpy

np - je skraćenica modulu numpy

## Počinjemo raditi sa numpy-em

Numpy se najviše koristi za rad sa listama, matricama i tensorima, pa ćemo krenuti od toga

In [2]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] # listu u pythonu pravimo sa uglastim zagradama

Da bi mogli koristiti napravljenu listu u numpy-u moramo joj dati numpy strukturu podatka odnosno numpy array

In [3]:
lista_numpy = np.array(lista, dtype=np.int32)

np - je naša skraćenica za numpy

array - je funkcija numpy-a koja će našu listu pretvoriti u numpy array

dtype - je vrsta podatka koju želimo dodjeliti našoj listi, oni koji se do sada nisu susretali sa tipovima podataka, int je podatak koji nema decimala, float je tip podatka koji ima decimale te ima veći opseg vrijednosti nego int

Hajmo kreriati još numpy array-a, ali sa različitim dimenzijama

In [4]:
dvodimenzijalni_array = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])

In [5]:
trodimenzijalni_array = np.array(
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15]]
)

Zašto ovo radimo? Pa zato jer će nam trebati u budućnosti kada budemo trebali kreirati vlastite strukture podataka koje će biti tražene od nas kako bi ih mogli ubaciti u algoritam da bi dobili naša riješenja

Da bi provjerili dimenzionalnost našeg array-a u nastavku naziva varijable dodajemo nastavak .shape

In [6]:
print(f"Jednodimenzionalni_array(lista_numpy): {lista_numpy.shape}")
print(f"Dvodimenzionalni_array: {dvodimenzijalni_array.shape}")
print(f"Trodimenzijalnu_array: {trodimenzijalni_array.shape}")

Jednodimenzionalni_array(lista_numpy): (10,)
Dvodimenzionalni_array: (2, 5)
Trodimenzijalnu_array: (3, 5)


Ako želimo ispisati nešto na ekranu koristimo print(), ako želimo ubaciti varijablu u print(f"") dodajemo f"{naziv varijable}", zapamtite da za svaki naziv varijable moramo imati prvo vitičaste zagrade i unutar njih naziv varijable

Prvi broj u zagradi je dimenzija, a drugi broj ćelija koji posjeduje

In [7]:
print(f"Jednodimenzionalni array:\n {lista_numpy}\n") # \n predstavlja novi red
print(f"Dvodimenzionalni array:\n {dvodimenzijalni_array}\n")
print(f"Trodimenzionalni array:\n {trodimenzijalni_array}\n")

Jednodimenzionalni array:
 [ 1  2  3  4  5  6  7  8  9 10]

Dvodimenzionalni array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Trodimenzionalni array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]



Da bi promjenili dimenzionalnost array-u koristimo funkciju .reshape

In [8]:
print(dvodimenzijalni_array.reshape(1, 10))

[[ 1  2  3  4  5  6  7  8  9 10]]


Uz numyp dobijamo i neke generičke funkcije kao što su min, max, sum, average

In [9]:
np.sum(dvodimenzijalni_array)

55

Još jedan primjer prije kraja jeste da numpy može generirati random brojeve za nas 

In [10]:
brojevi = np.arange(start=0, stop=10, step=1) # step je broj za koliko će se uvećavati od starta do stopa
brojevi

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

U narednim izlaganjima koja se budu ticala ML-a i DL-a dosta ćemo raditi sa petljama tako da ćemo i ovde dati nekoliko primjera for petlje

In [11]:
for i in brojevi: 
    print(i)

0
1
2
3
4
5
6
7
8
9


brojevi = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 

u prvom krugu i = brojevi u indexsu 0 
u drugom krugu i se povećava za jedan i = brojevi u indexu 1
 
i tako sve do kraja našeg array-a brojevi

Sličnu stvar možemo uraditi i ovako